//import setup from "../../js/setup";

import { colors, fonts, typography } from "../../js/setup";

//const { colors, fonts } = setup;

const theme = {
    fontFamily: fonts.primary,
    fontSize: {
        xsmall: "1.2rem",
        small: "1.3rem",
        medium: "1.6rem",
        large: "1.6rem",
    },
    fontWeight: "400",
    buttonHeight: {
        xsmall: "2.8rem",
        small: "3.2rem",
        medium: "3.6rem",
        large: "4.0rem",
    },
    buttonWidth: {
        xsmall: "8rem",
        small: "10rem",
        medium: "12.5rem",
        large: "13.5rem",
    },
    borderThickness: ".1rem",
    borderStyle: "solid",
    borderColor: {
        primary: {
            default: colors.defaultAccent,
            accept: colors.acceptAccent,
            reject: colors.rejectAccent,
            inform: colors.informAccent,
            warn: colors.warnAccent,
        },
        secondary: {
            default: colors.defaultAccent,
            accept: colors.acceptAccent,
            reject: colors.rejectAccent,
            inform: colors.informAccent,
            warn: colors.warnAccent,
        },
        text: {
            default: "transparent",
            accept: "transparent",
            reject: "transparent",
            inform: "transparent",
            warn: "transparent",
        },
    },
    borderColorHover: {
        primary: {
            default: colors.defaultAccentLight,
            accept: colors.acceptAccentLight,
            reject: colors.rejectAccentLight,
            inform: colors.informAccentLight,
            warn: colors.warnAccentLight,
        },
        secondary: {
            default: colors.defaultAccent,
            accept: colors.acceptAccent,
            reject: colors.rejectAccent,
            inform: colors.informAccent,
            warn: colors.warnAccent,
        },
        text: {
            default: "transparent",
            accept: "transparent",
            reject: "transparent",
            inform: "transparent",
            warn: "transparent",
        },
    },
    borderColorActive: {
        primary: {
            default: colors.defaultAccentDark,
            accept: colors.acceptAccentDark,
            reject: colors.rejectAccentDark,
            inform: colors.informAccentDark,
            warn: colors.warnAccentDark,
        },
        secondary: {
            default: colors.defaultAccentDark,
            accept: colors.acceptAccentDark,
            reject: colors.rejectAccentDark,
            inform: colors.informAccentDark,
            warn: colors.warnAccentDark,
        },
        text: {
            default: "transparent",
            accept: "transparent",
            reject: "transparent",
            inform: "transparent",
            warn: "transparent",
        },
    },
    backgroundColor: {
        primary: {
            default: colors.defaultAccent,
            accept: colors.acceptAccent,
            reject: colors.rejectAccent,
            inform: colors.informAccent,
            warn: colors.warnAccent,
        },
        secondary: {
            default: colors.white,
            accept: colors.white,
            reject: colors.white,
            inform: colors.white,
            warn: colors.white,
        },
        text: {
            default: "transparent",
            accept: "transparent",
            reject: "transparent",
            inform: "transparent",
            warn: "transparent",
        },
    },
    backgroundColorHover: {
        primary: {
            default: colors.defaultAccentLight,
            accept: colors.acceptAccentLight,
            reject: colors.rejectAccentLight,
            inform: colors.informAccentLight,
            warn: colors.warnAccentLight,
        },
        secondary: {
            default: colors.defaultAccent,
            accept: colors.acceptAccent,
            reject: colors.rejectAccent,
            inform: colors.informAccent,
            warn: colors.warnAccent,
        },
        text: {},
    },
    backgroundColorActive: {
        primary: {
            default: colors.defaultAccentDark,
            accept: colors.acceptAccentDark,
            reject: colors.rejectAccentDark,
            inform: colors.informAccentDark,
            warn: colors.warnAccentDark,
        },
        secondary: {
            default: colors.defaultAccentDark,
            accept: colors.acceptAccentDark,
            reject: colors.rejectAccentDark,
            inform: colors.informAccentDark,
            warn: colors.warnAccentDark,
        },
        text: {},
    },
    labelColor: {
        primary: {
            default: colors.white,
            accept: colors.white,
            reject: colors.white,
            inform: colors.white,
            warn: colors.warnColor,
        },
        secondary: {
            default: colors.defaultAccent,
            accept: colors.acceptAccent,
            reject: colors.rejectAccent,
            inform: colors.informAccent,
            warn: colors.warnColor,
        },
        text: {
            default: colors.defaultAccent,
            accept: colors.acceptAccent,
            reject: colors.rejectAccent,
            inform: colors.informAccent,
            warn: colors.warnColor,
        },
    },
    labelColorHover: {
        primary: {
            default: colors.white,
            accept: colors.white,
            reject: colors.white,
            inform: colors.white,
            warn: colors.warnColor,
        },
        secondary: {
            default: colors.white,
            accept: colors.white,
            reject: colors.white,
            inform: colors.white,
            warn: colors.warnColor,
        },
        text: {
            default: colors.defaultAccentLight,
            accept: colors.acceptAccentLight,
            reject: colors.rejectAccentLight,
            inform: colors.informAccentLight,
            warn: colors.warnColor,
        },
    },
    labelColorActive: {
        primary: {
            default: colors.white,
            accept: colors.white,
            reject: colors.white,
            inform: colors.white,
            warn: colors.warnColor,
        },
        secondary: {
            default: colors.white,
            accept: colors.white,
            reject: colors.white,
            inform: colors.white,
            warn: colors.warnColor,
        },
        text: {
            default: colors.defaultAccentDark,
            accept: colors.acceptAccentDark,
            reject: colors.rejectAccentDark,
            inform: colors.informAccentDark,
            warn: colors.warnAccentDark,
        },
    },
    padding: {
        xsmall: ".7rem 1rem",
        small: ".9rem 2rem",
        medium: "1.1rem 3.2rem",
        large: "1.3rem 4rem",
    },
    paddingWithIcon: {
        xsmall: ".7rem .6rem",
        small: ".9rem 1rem",
        medium: "1.1rem 1.6rem",
        large: "1.3rem 2.4rem",
    },
    iconMargin: {
        xsmall: ".4rem",
        small: ".6rem",
        medium: ".8rem",
        large: "1.2rem",
    },
    margin: ".4rem",
    disabled: {
        bgColor: colors.disabledAccent,
        borderColor: colors.disabledAccent,
        color: colors.white,
    },
    // fontFamily: fonts.fontstack1,
    // fontSize: "1.6rem",
    // borderRadius: "0rem",
    // outlined: {
    //     bgColor: {
    //         positive: colors.white,
    //         negative: colors.white,
    //         information: colors.white,
    //         system: colors.white,
    //     },
    //     bgHoverColor: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.systemAccent,
    //     },
    //     color: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.systemAccent,
    //     },
    //     colorHover: {
    //         positive: colors.white,
    //         negative: colors.white,
    //         information: colors.white,
    //         system: colors.white,
    //     },
    //     borderWidth: ".1rem",
    //     borderStyle: "solid",
    //     borderColor: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.systemAccent,
    //     },
    //     borderHoverColor: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.systemAccent,
    //     },
    //     leftMargin: ".4rem",
    //     rightMargin: ".4rem",
    //     padding: "1.2rem 2.0rem",
    // },
    // solid: {
    //     bgColor: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.white,
    //     },
    //     bgHoverColor: {
    //         positive: colors.positiveAccentLight,
    //         negative: colors.negativeAccentLight,
    //         information: colors.informationAccentLight,
    //         system: colors.systemAccentLight,
    //     },
    //     color: {
    //         positive: colors.white,
    //         negative: colors.white,
    //         information: colors.white,
    //         system: colors.systemAccent,
    //     },
    //     colorHover: {
    //         positive: colors.white,
    //         negative: colors.white,
    //         information: colors.white,
    //         system: colors.white,
    //     },
    //     borderWidth: ".1rem",
    //     borderStyle: "solid",
    //     borderColor: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.systemAccent,
    //     },
    //     borderHoverColor: {
    //         positive: colors.positiveAccentLight,
    //         negative: colors.negativeAccentLight,
    //         information: colors.informationAccentLight,
    //         system: colors.systemAccentLight,
    //     },
    //     leftMargin: ".4rem",
    //     rightMargin: ".4rem",
    //     padding: "1.2rem 2.0rem",
    // },
    // text: {
    //     bgColor: {
    //         positive: "transparent",
    //         negative: "transparent",
    //         information: "transparent",
    //         system: "transparent",
    //     },
    //     bgHoverColor: {
    //         positive: colors.grey300,
    //         negative: colors.grey300,
    //         information: colors.grey300,
    //         system: colors.grey300,
    //     },
    //     color: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.systemAccent,
    //     },
    //     colorHover: {
    //         positive: colors.positiveAccent,
    //         negative: colors.negativeAccent,
    //         information: colors.informationAccent,
    //         system: colors.systemAccent,
    //     },
    //     borderWidth: ".1rem",
    //     borderStyle: "solid",
    //     borderColor: {
    //         positive: "transparent",
    //         negative: "transparent",
    //         information: "transparent",
    //         system: "transparent",
    //     },
    //     borderHoverColor: {
    //         positive: "transparent",
    //         negative: "transparent",
    //         information: "transparent",
    //         system: "transparent",
    //     },
    //     leftMargin: ".4rem",
    //     rightMargin: ".4rem",
    //     padding: "1.2rem 2.0rem",
    // },
    // disabled: {
    //     bgColor: colors.disabledAccent,
    //     borderColor: colors.disabledAccent,
    //     color: colors.white,
    // },
};

export default theme;
