import { lighten, darken } from "polished";

const baseColors = {
    black: "#000000",
    white: "#ffffff",
    grey50: "#fafafa",
    grey100: "#f5f5f5",
    grey200: "#eeeeee",
    grey300: "#e0e0e0",
    grey400: "#bdbdbd",
    grey500: "#9e9e9e",
    grey600: "#757575",
    grey700: "#616161",
    grey800: "#424242",
    grey900: "#212121",
    red: "#d32f2f",
    amber: "#ffc107",
    green: "#4caf50",
    blue: "#2196f3",
    brown: "#795548",
};

const colors = {
    white: baseColors.white,
    black: baseColors.black,
    grey50: baseColors.grey50,
    grey100: baseColors.grey100,
    grey200: baseColors.grey200,
    grey300: baseColors.grey300,
    grey400: baseColors.grey400,
    grey500: baseColors.grey500,
    grey600: baseColors.grey600,
    grey700: baseColors.grey700,
    grey800: baseColors.grey800,
    grey900: baseColors.grey900,
    textLight: baseColors.grey600,
    textDark: baseColors.grey900,

    defaultAccent: baseColors.grey900,
    defaultAccentLight: lighten(0.1, baseColors.grey900),
    defaultAccentDark: darken(0.1, baseColors.grey900),
    acceptAccent: baseColors.green,
    acceptAccentLight: lighten(0.1, baseColors.green),
    acceptAccentDark: darken(0.1, baseColors.green),
    rejectAccent: baseColors.red,
    rejectAccentLight: lighten(0.1, baseColors.red),
    rejectAccentDark: darken(0.1, baseColors.red),
    informAccent: baseColors.blue,
    informAccentLight: lighten(0.1, baseColors.blue),
    informAccentDark: darken(0.1, baseColors.blue),
    warnAccent: baseColors.amber,
    warnAccentLight: lighten(0.1, baseColors.amber),
    warnAccentDark: darken(0.1, baseColors.amber),
    warnColor: baseColors.brown,

    positiveAccent: baseColors.green,
    positiveAccentLight: lighten(0.1, baseColors.green),
    positiveAccentDark: darken(0.1, baseColors.green),
    negativeAccent: baseColors.red,
    negativeAccentLight: lighten(0.1, baseColors.red),
    negativeAccentDark: darken(0.1, baseColors.red),
    informationAccent: baseColors.blue,
    informationAccentLight: lighten(0.1, baseColors.blue),
    informationAccentDark: darken(0.1, baseColors.blue),
    systemAccent: baseColors.grey900,
    systemAccentLight: lighten(0.1, baseColors.grey900),
    systemAccentDark: darken(0.1, baseColors.grey900),
    warningAccent: baseColors.amber,
    warningText: baseColors.brown,
    disabledAccent: baseColors.grey400,
};

export default colors;
